export default {
  ADD_TO_BASKET: 'ADD_TO_BASKET',
  REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
  REMOVE_ALL_FROM_BASKET: 'REMOVE_ALL_FROM_BASKET',
  CHANGE_CANTIDAD_BASKET: 'CHANGE_CANTIDAD_BASKET',
}